// Demo data for co-founder / investor walkthroughs. Loaded into the in-memory
// store ONLY when AI2B_DEMO=1 (see lib/config.ts DEMO_MODE + leadStore). In demo
// mode the app ignores Supabase entirely, so this never touches real data — it's
// a self-contained, fully-working sandbox where every admin feature (assign,
// payment, amount, outcome, AI-draft rating, deliverables) is already populated.
//
// Assignments reference the seeded designer ids from lib/expertStore
// (seed-nino / seed-giorgi / seed-tamar / seed-ana). Dates are fixed strings so
// the seed is deterministic (no churn across runs).
import type { StoredLead } from "@/lib/leadStore";

export const DEMO_LEADS: StoredLead[] = [
  {
    id: "demo-1",
    created_at: "2026-07-14T09:12:00.000Z",
    status: "done",
    name: "ნინი ბერიძე",
    phone: "+995 599 21 33 44",
    email: "nini@brew.ge",
    business_type: "კაფე",
    category: "დიზაინი/ბრენდინგი",
    required_skills: ["logo", "branding"],
    ai_relevant: false,
    summary: "ახალი specialty-კაფის ლოგო + ბრენდბუქი.",
    advice:
      "მინიმალისტური wordmark + მარცვლის ნიშანი; თბილი პალიტრა (ყავისფერი/კრემისფერი); მენიუსა და ჭიქებზე გამოსაყენებელი ვერსიები. ბრენდბუქი: ლოგოს ვარიაციები, ფერები, ტიპოგრაფია.",
    assigned_expert_id: "seed-nino",
    assigned_expert_name: "ნინო კაპანაძე",
    payment_status: "paid",
    amount: 1200,
    outcome: "won",
    ai_draft_status: "accepted",
    deliverables: [
      { url: "https://example.com/demo/brew-logo.png", name: "brew-logo-final.png", type: "image/png", size: 482000, isImage: true },
      { url: "https://example.com/demo/brew-brandbook.pdf", name: "brew-brandbook.pdf", type: "application/pdf", size: 1840000, isImage: false },
    ],
  },
  {
    id: "demo-2",
    created_at: "2026-07-13T14:40:00.000Z",
    status: "done",
    name: "გიორგი ტატიშვილი",
    phone: "+995 555 88 12 90",
    email: "g.tati@fitzone.ge",
    business_type: "ფიტნეს-სტუდია",
    category: "დიზაინი/ბრენდინგი",
    required_skills: ["social_media", "poster"],
    ai_relevant: true,
    summary: "სოც. მედია პაკეტი — 12 პოსტის შაბლონი Instagram-ისთვის.",
    advice:
      "ერთიანი grid-ესთეტიკა; 3 შაბლონის ტიპი (აქცია / განრიგი / მოტივაცია); მუქი ფონი + ენერგიული აქცენტი. AI-workflow-ით სწრაფი ვარიაციები.",
    assigned_expert_id: "seed-giorgi",
    assigned_expert_name: "გიორგი მჭედლიძე",
    payment_status: "paid",
    amount: 650,
    outcome: "won",
    ai_draft_status: "edited",
    deliverables: [
      { url: "https://example.com/demo/fit-templates.pdf", name: "instagram-templates.pdf", type: "application/pdf", size: 2200000, isImage: false },
    ],
  },
  {
    id: "demo-3",
    created_at: "2026-07-12T11:05:00.000Z",
    status: "done",
    name: "ანა კვარაცხელია",
    phone: "+995 598 44 22 10",
    email: "ana@lumebeauty.ge",
    business_type: "სილამაზის სალონი",
    category: "დიზაინი/ბრენდინგი",
    required_skills: ["ui_ux", "illustration"],
    ai_relevant: false,
    summary: "ჯავშნის landing-გვერდის UI-კონცეფცია.",
    advice:
      "ერთ-გვერდიანი landing: hero + სერვისები + ჯავშნის ფორმა; რბილი პასტელი; მობილურ-პირველი. ილუსტრირებული აქცენტები სექციებისთვის.",
    assigned_expert_id: "seed-ana",
    assigned_expert_name: "ანა ხურციძე",
    payment_status: "invoiced",
    amount: 900,
    outcome: "pending",
    ai_draft_status: "rejected",
  },
  {
    id: "demo-4",
    created_at: "2026-07-14T16:20:00.000Z",
    status: "in_progress",
    name: "დავით ლომიძე",
    phone: "+995 577 30 99 15",
    email: "davit@greenmarket.ge",
    business_type: "ონლაინ მაღაზია",
    category: "დიზაინი/ბრენდინგი",
    required_skills: ["logo", "business_card"],
    ai_relevant: false,
    summary: "ეკო-პროდუქტების მაღაზიის ლოგო + სავიზიტო.",
    advice:
      "ბუნებრივი, ორგანული ფორმა; მწვანე პალიტრა; ლოგო + სავიზიტოს ორმხრივი დიზაინი. მინიმალიზმი, გადამუშავებადი მასალის ესთეტიკა.",
    assigned_expert_id: "seed-tamar",
    assigned_expert_name: "თამარ ბერიძე",
    payment_status: "unpaid",
    amount: 750,
    outcome: "pending",
    ai_draft_status: "unset",
  },
  {
    id: "demo-5",
    created_at: "2026-07-15T08:02:00.000Z",
    status: "new",
    name: "მარიამ ჩხაიძე",
    phone: "+995 591 12 45 78",
    email: "mariam@dolce.ge",
    business_type: "საკონდიტრო",
    category: "დიზაინი/ბრენდინგი",
    required_skills: ["branding", "poster"],
    ai_relevant: false,
    summary: "საკონდიტროს ბრენდინგი + სადღესასწაულო პოსტერები.",
    advice:
      "ელეგანტური, ხელნაწერი-ტიპოგრაფიის ლოგო; ოქროსფერი აქცენტი; სეზონური პოსტერების სერია. პრემიუმ განცდა.",
    payment_status: "unpaid",
    amount: 0,
    outcome: "pending",
    ai_draft_status: "unset",
  },
  {
    id: "demo-6",
    created_at: "2026-07-15T10:35:00.000Z",
    status: "new",
    name: "ლევან გოგიჩაიშვილი",
    phone: "+995 574 66 00 21",
    email: "levan@urbancuts.ge",
    business_type: "ბარბერშოპი",
    category: "Marketing",
    required_skills: ["social_media"],
    ai_relevant: true,
    summary: "Instagram-ის კონტენტ-სტრატეგია + პირველი კამპანია.",
    advice:
      "ლოკალური targeting; before/after Reels; მუდმივი posting-გრაფიკი. AI-ით hook-ების და caption-ების ვარიაციები.",
    payment_status: "unpaid",
    amount: 0,
    outcome: "pending",
    ai_draft_status: "unset",
  },
  {
    id: "demo-7",
    created_at: "2026-07-11T13:50:00.000Z",
    status: "done",
    name: "სოფო მელაძე",
    phone: "+995 596 77 88 33",
    email: "sopo@petshop.ge",
    business_type: "ცხოველების მაღაზია",
    category: "დიზაინი/ბრენდინგი",
    required_skills: ["logo", "illustration"],
    ai_relevant: false,
    summary: "მხიარული ლოგო + ილუსტრირებული პერსონაჟი.",
    advice:
      "მეგობრული talismani (ცხოველი); ნათელი ფერები; ლოგო + პერსონაჟის რამდენიმე პოზა შეფუთვისთვის და სოც. მედიისთვის.",
    assigned_expert_id: "seed-ana",
    assigned_expert_name: "ანა ხურციძე",
    payment_status: "paid",
    amount: 820,
    outcome: "won",
    ai_draft_status: "accepted",
    deliverables: [
      { url: "https://example.com/demo/pet-mascot.png", name: "mascot-poses.png", type: "image/png", size: 690000, isImage: true },
    ],
  },
  {
    id: "demo-8",
    created_at: "2026-07-10T09:25:00.000Z",
    status: "done",
    name: "ირაკლი ნადირაძე",
    phone: "+995 599 03 14 27",
    email: "irakli@techsupport.ge",
    business_type: "IT სერვისი",
    category: "დიზაინი/ბრენდინგი",
    required_skills: ["logo", "ui_ux"],
    ai_relevant: false,
    summary: "B2B ბრენდის ლოგო + პრეზენტაციის შაბლონი.",
    advice:
      "სანდო, ტექნოლოგიური wordmark; ლურჯი პალიტრა; slide-master შაბლონი გაყიდვების დეკებისთვის.",
    assigned_expert_id: "seed-tamar",
    assigned_expert_name: "თამარ ბერიძე",
    payment_status: "invoiced",
    amount: 1400,
    outcome: "lost",
    ai_draft_status: "edited",
  },
];
